# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: Region
  displayName: Region
  type: string
  default:
  values:
  - Projects_AME
  - Projects_APAC
  - Projects_EMEA

- name: pndemeaOrder
  type: boolean
  default: false  
  
- name: pndemeaOmsApi
  type: boolean
  default: false 

- name: pndemeaNotifications
  type: boolean
  default: false 

- name: pndemeaCatalogOmsEod
  type: boolean
  default: false 

- name: pndemeaInventory
  type: boolean
  default: false 

stages:
  - stage : QA 
    jobs:
    - job : qa_build
      displayName : qa_build
      steps:
        - script :  echo building $(qa_build.BuildNumber) with ${{parameters.Region}}
    - job: pndemeaorder
      displayName: 
      steps:
        - script: echo "going to condition"  
        - ${{ if contains(parameters.pndemeaorder, true) }}:   
          - script: echo "Runnning pndemea-order" 
          - template: pndemeaOrder.yml

    - job: pndemeaOmsApi
      displayName: 
      steps:
        - script: echo "going to condition" 
        - ${{ if contains(parameters.pndemeaOmsApi, true) }}:  
          - script: echo "Runnning pndemeaOmsApi"  
          - template: pndemeaOmsApi.yml

    - job: pndemeaNotifications
      displayName: 
      steps:  
        - script: echo "going to condition" 
        - ${{ if contains(parameters.pndemeaNotifications, true) }}:  
          - script: echo "Runnning pndemeaNotifications"  
          - template: pndemeaNotifications.yml

    - job: pndemeaCatalogOmsEod
      displayName: 
      steps:
        - script: echo "going to condition" 
        - ${{ if contains(parameters.pndemeaCatalogOmsEod, true) }}:  
          - script: echo "Runnning pndemeaCatalogOmsEod"  
          - template: pndemeaCatalogOmsEod.yml

    - job: pndemeaInventory
      displayName: 
      steps:
        - script: echo "going to condition" 
        - ${{ if contains(parameters.pndemeaInventory, true) }}:  
          - script: echo "Runnning pndemeaInventory"  
          - template: pndemeaInventory.yml

    # - job: pndemeaOmsApi
    #   displayName: pndemeaOmsApiJob
    #   steps:
    #     - script: echo "Runnning pndemea-oms-api"
    #     - template: pndemeaOmsApi.yml
          
    #     - ${{ if contains(parameters.pndemeaNotifications, true) }}:  
    # - job: pndemeaNotifications
    #   displayName: pndemeaNotificationsJob
    #   steps:
    #     - script: echo "Runnning pndemea-notifications"
    #     - template: pndemeaNotifications.yml

    #     - ${{ if contains(parameters.pndemeaCatalogOmsEod, true) }}:    
    # - job: pndemeaCatalogOmsEod
    #   displayName: pndemeaCatalogOmsEod
    #   steps:
    #     - script: echo "Runnning pndemeaCatalogOmsEod"  
    #     - template: pndemeaCatalogOmsEod.yml

    #     - ${{ if contains(parameters.pndemeaInventory, true) }}:  
    # - job: pndemeaInventory
    #   displayName: pndemeaInventory
    #   steps:
    #     - script: echo "Runnning pndemeaInventory"     
    #     - template: pndemeaInventory.yml
      
          
          #   condition: and(succeeded(), eq('${{ parameters.pndemeaOrder }}', 'true'))
          # # - ${{ if contains(parameters.pndemeaorder, true) }}:
          #   - template : pndemeaOrder.yml
        
  #       - job :
            
  #         - ${{ if contains(parameters.pndemeaOmsApi, true) }}:
  #           - script: echo "Runnning pndemea-oms-api"
  #         - job :
  #           - template : pndemeaOmsApi.yml
  #         - ${{ if contains(parameters.pndemeaNotifications, true) }}:
  #           - script: echo "Runnning pndemea-notifications"
  #         - job :
  #           - template : pndemeaNotifications.yml
  #         - ${{ if contains(parameters.pndemeaCatalogOmsEod, true) }}:
  #           - script: echo "Runnning pndemea-catalog-oms-eod"
  #         - job :
  #           - template : pndemeaCatalogOmsEod.yml
  #         - ${{ if contains(parameters.pndemeaInventory, true) }}:
  #           - script: echo "Runnning pndemea-inventory"
  #         - job :
  #           - template : pndemeaInventory.yml
  # - stage : DEV
  #   # jobs:
  #   # - job : dev_build
  #   #   displayName : dev_build
  #     steps:
  #     - script : |
  #               echo building $(dev_build.BuildNumber) with ${{parameters.Region}}
  #       - ${{ if contains(parameters.pndemeaorder, true) }}:
  #         - script: echo "Runnning pndemea-order"
  #         - job :
  #           - template : pndemeaOrder.yml
  #         - ${{ if contains(parameters.pndemeaOmsApi, true) }}:
  #           - script: echo "Runnning pndemea-oms-api"
  #         - job :
  #           - template : pndemeaOmsApi.yml
  #         - ${{ if contains(parameters.pndemeaNotifications, true) }}:
  #           - script: echo "Runnning pndemea-notifications"
  #         - job :
  #           - template : pndemeaNotifications.yml
  #         - ${{ if contains(parameters.pndemeaCatalogOmsEod, true) }}:
  #           - script: echo "Runnning pndemea-catalog-oms-eod"
  #         - job :
  #           - template : pndemeaCatalogOmsEod.yml
  #         - ${{ if contains(parameters.pndemeaInventory, true) }}:
  #           - script: echo "Runnning pndemea-inventory"
  #         - job :
  #           - template : pndemeaInventory.yml
  # - stage : PREPROD
  #   # jobs:
  #   # - job : preprod_build
  #   #   displayName : preprod_build
  #     steps:
  #     - script : |
  #               echo building $(preprod_build.BuildNumber) with ${{parameters.Region}}
  #       - ${{ if contains(parameters.pndemeaorder, true) }}:
  #         - script: echo "Runnning pndemea-order"
  #         - job :
  #           - template : pndemeaOrder.yml
  #         - ${{ if contains(parameters.pndemeaOmsApi, true) }}:
  #           - script: echo "Runnning pndemea-oms-api"
  #         - job :
  #           - template : pndemeaOmsApi.yml
  #         - ${{ if contains(parameters.pndemeaNotifications, true) }}:
  #           - script: echo "Runnning pndemea-notifications"
  #         - job :
  #           - template : pndemeaNotifications.yml
  #         - ${{ if contains(parameters.pndemeaCatalogOmsEod, true) }}:
  #           - script: echo "Runnning pndemea-catalog-oms-eod"
  #         - job :
  #           - template : pndemeaCatalogOmsEod.yml
  #         - ${{ if contains(parameters.pndemeaInventory, true) }}:
  #           - script: echo "Runnning pndemea-inventory"
  #         - job :
  #           - template : pndemeaInventory.yml         
  # - stage : PROD
  #   # jobs:
  #   # - job : prod_build
  #   #   displayName : prod_build
  #     steps:
  #     - script : |
  #               echo building $(prod_build.BuildNumber) with ${{parameters.Region}}
  #       - ${{ if contains(parameters.pndemeaorder, true) }}:
  #         - script: echo "Runnning pndemea-order"
  #         - job :
  #           - template : pndemeaOrder.yml
  #         - ${{ if contains(parameters.pndemeaOmsApi, true) }}:
  #           - script: echo "Runnning pndemea-oms-api"
  #         - job :
  #           - template : pndemeaOmsApi.yml
  #         - ${{ if contains(parameters.pndemeaNotifications, true) }}:
  #           - script: echo "Runnning pndemea-notifications"
  #         - job :
  #           - template : pndemeaNotifications.yml
  #         - ${{ if contains(parameters.pndemeaCatalogOmsEod, true) }}:
  #           - script: echo "Runnning pndemea-catalog-oms-eod"
  #         - job :
  #           - template : pndemeaCatalogOmsEod.yml
  #         - ${{ if contains(parameters.pndemeaInventory, true) }}:
  #           - script: echo "Runnning pndemea-inventory"
  #         - job :
  #           - template : pndemeaInventory.yml          






